### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [mircokroon/minecraft-world-downloader-launcher#1]
```
java.lang.ArrayIndexOutOfBoundsException: Index 20 out of bounds for length 20
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:198)
	at java.base/java.io.InputStream.read(InputStream.java:296)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:208)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:195)
	at packets.handler.version.ClientBoundGamePacketHandler_1_18.lambda$new$1(ClientBoundGamePacketHandler_1_18.java:32)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.RuntimeException: VarInt is too big
	at packets.DataReader.readVarInt(DataReader.java:94)
	at packets.DataReader.readVarInt(DataReader.java:68)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.entity.EntityRegistry.destroyEntities(EntityRegistry.java:187)
	at packets.handler.ClientBoundGamePacketHandler.lambda$new$5(ClientBoundGamePacketHandler.java:60)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 12 out of bounds for byte[5]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 12 out of bounds for byte[5]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.dimension.DimensionCodec.getDimensions()" because the return value of "game.data.WorldManager.getDimensionCodec()" is null
	at game.data.LevelData.disableWorldGeneration(LevelData.java:227)
	at game.data.LevelData.save(LevelData.java:174)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.save(WorldManager.java:437)
	at game.data.WorldManager.save(WorldManager.java:467)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 12 out of bounds for byte[5]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[9]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.NullPointerException: Cannot invoke "game.data.dimension.DimensionCodec.getDimensions()" because the return value of "game.data.WorldManager.getDimensionCodec()" is null
	at game.data.LevelData.disableWorldGeneration(LevelData.java:227)
	at game.data.LevelData.save(LevelData.java:174)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.save(WorldManager.java:437)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 12 out of bounds for byte[5]

 java.lang.NullPointerException: Cannot invoke "game.data.dimension.DimensionCodec.getDimensions()" because the return value of "game.data.WorldManager.getDimensionCodec()" is null
	at game.data.LevelData.disableWorldGeneration(LevelData.java:227)
	at game.data.LevelData.save(LevelData.java:174)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.save(WorldManager.java:437)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[9]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:37)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 12 out of bounds for byte[5]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.dimension.DimensionCodec.getDimensions()" because the return value of "game.data.WorldManager.getDimensionCodec()" is null
	at game.data.LevelData.disableWorldGeneration(LevelData.java:227)
	at game.data.LevelData.save(LevelData.java:174)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.save(WorldManager.java:437)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[9]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 12 out of bounds for byte[5]

 java.lang.NullPointerException: Cannot invoke "game.data.dimension.DimensionCodec.getDimensions()" because the return value of "game.data.WorldManager.getDimensionCodec()" is null
	at game.data.LevelData.disableWorldGeneration(LevelData.java:227)
	at game.data.LevelData.save(LevelData.java:174)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.save(WorldManager.java:437)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by mircokroon** [comment]
Wrong project, this is only for the launcher
